### ISSUE TITLE
proper tagged metrics for datadog

### ISSUE THREAD

**Issue by jippi** [Graylog2/graylog-plugin-metrics-reporter#24]
today the datadog version send plain old statsd events to the datadog backend

## Example 1 

`graylog_performance.org.graylog2.inputs.extractors.RegexExtractor.regex.cee156be_a210_40b4_8533_efead31f420b.completeExecutionTime.stddev` 

->

`graylog_performance.org.graylog2.inputs.extractors.RegexExtractor.regex.completeExecutionTime.stddev` 

with tag 

`regex_id=cee156be_a210_40b4_8533_efead31f420b` instead

## Example 2

`graylog_performance.org.graylog2.inputs.gelf.tcp.GELFTCPInput.5902685b9b54a94e0e4f76f6.total_connections`

->

`graylog_performance.org.graylog2.inputs.gelf.tcp.GELFTCPInput.total_connections`

with tag

`output_id=5902685b9b54a94e0e4f76f6`

so one unique statsd key, and encode the variance in named tags - [see datadog datagram format](http://docs.datadoghq.com/guides/dogstatsd/#datagram-format)

Outputting things the way they are now, make them close to useless in the datadog UI, and will take up ~11k metrics (you pay per metric)

**Comment by joschi** [comment]
@jippi That's currently not possible, because Graylog is using [Dropwizard Metrics](http://metrics.dropwizard.io/) internally which doesn't support tags.

We don't have the resources nor the intention to change this in the short or middle term.
This being said, PRs for implementing extracting tags from these metric names are welcome!

**Comment by jippi** [comment]
Thanks @joschi :)
